services:
  flet-app:
    container_name: flet_gpt_chat
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: sh -c "flet run --web --host 0.0.0.0 --port 8009 main.py"
    ports:
      - "8009:8009"
    volumes:
      - /home/den/.aws:/root/.aws/
    networks:
      - flet_network
    restart: always

networks:
  flet_network:
    name: "flet_network"
